const app=document.getElementById('app');let state={tab:'Chat',status:{},config:{},activity:[],messages:[],permission:null};
async function api(u,o){let r=await fetch(u,{headers:{'Content-Type':'application/json'},...o});let j=await r.json();if(!r.ok)throw new Error(j.detail||'Request failed');return j}
async function load(){state.status=await api('/api/status');state.config=await api('/api/config');state.activity=await api('/api/activity');render()}
function esc(s){return String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function render(){app.innerHTML=`<div class="app"><header class="header"><div class="row"><div><div class="brand">CLI-KML</div><div class="muted">${esc(state.status.workspace||'No workspace')}</div></div><div class="status">● ${state.status.connected?'Connected':'Not configured'}</div></div></header><main class="content">${state.tab==='Chat'?chat():state.tab==='Project'?project():state.tab==='Activity'?activity():settings()}</main><nav class="nav">${['Chat','Project','Activity','Settings'].map(x=>`<button onclick="state.tab='${x}';render()">${x}</button>`).join('')}</nav></div>${state.permission?permissionModal():''}`}
function chat(){return `<div class="card"><div class="muted">Model</div><b>${esc(state.status.model||'—')}</b></div><div class="chat">${state.messages.map(m=>`<div class="bubble ${m.role==='user'?'user':'agent'}"><b>${m.role==='user'?'YOU':'CLI-KML AGENT'}</b><div>${esc(m.content)}</div></div>`).join('')}</div><div class="composer"><textarea id="msg" class="input" rows="1" placeholder="Tulis pesan..."></textarea><button class="primary" onclick="send()">➤</button></div>`}
async function send(){let el=document.getElementById('msg'),v=el.value.trim();if(!v)return;state.messages.push({role:'user',content:v});render();try{let j=await api('/api/chat',{method:'POST',body:JSON.stringify({message:v})});state.messages.push({role:'assistant',content:j.answer})}catch(e){state.messages.push({role:'assistant',content:'Error: '+e.message})}render()}
function treeHtml(nodes){return '<ul>'+nodes.map(n=>`<li>${n.type==='directory'?'📁':'📄'} ${esc(n.name)}${n.children?treeHtml(n.children):` <button onclick="openFile('${encodeURIComponent(n.path)}')">Open</button>`}</li>`).join('')+'</ul>'}
async function project(){let j=await api('/api/project/tree');return `<div class="card"><div class="muted">Workspace</div><b>${esc(j.workspace)}</b></div><div class="card">${treeHtml(j.tree)}</div><div id="file"></div>`}
async function openFile(path){let j=await api('/api/project/file?path='+path);document.getElementById('file').innerHTML=`<div class="card"><b>${esc(j.data.path)}</b><pre>${esc(j.data.content)}</pre></div>`}
function activity(){return `<div class="card"><b>Activity</b><div class="timeline">${state.activity.slice().reverse().map(e=>`<div class="card"><b>${esc(e.type)}</b><div class="muted">${esc(e.message||e.tool||'')}</div>${e.result?`<pre>${esc(JSON.stringify(e.result,null,2))}</pre>`:''}</div>`).join('')||'<div class="muted">No activity yet.</div>'}</div></div>`}
function settings(){let p=state.config.providers?.[state.config.active_provider]||{};return `<div class="card"><h3>Provider</h3><input id="base" class="input" value="${esc(p.base_url||'https://api.openai.com/v1')}" placeholder="Base URL"><input id="key" class="input" type="password" placeholder="API Key (leave blank to keep existing)"><input id="model" class="input" value="${esc(state.config.active_model||'gpt-4o-mini')}" placeholder="Model"><input id="ws" class="input" value="${esc(state.config.workspace||'')}" placeholder="Workspace path"><div class="row"><button onclick="saveCfg()">Save Settings</button><button onclick="testConn()">Test Connection</button></div><div id="settingsMsg" class="muted"></div></div>`}
async function saveCfg(){let body={base_url:document.getElementById('base').value,model:document.getElementById('model').value,workspace:document.getElementById('ws').value};let k=document.getElementById('key').value;if(k)body.api_key=k;try{state.config=await api('/api/config',{method:'POST',body:JSON.stringify(body)});state.status=await api('/api/status');document.getElementById('settingsMsg').textContent='✓ Saved'}catch(e){document.getElementById('settingsMsg').textContent='✗ '+e.message}}
async function testConn(){let x=document.getElementById('settingsMsg');x.textContent='Testing...';try{let j=await api('/api/test-connection',{method:'POST',body:'{}'});x.textContent=`✓ Connection successful · ${j.latency_ms} ms · ${j.model}`}catch(e){x.textContent='✗ '+e.message}}
function permissionModal(){let e=state.permission;return `<div class="composer" style="top:30%;bottom:auto;border:1px solid var(--border);border-radius:16px;display:block"><b>Permission Required</b><p>AI wants to use <code>${esc(e.tool)}</code></p><pre>${esc(JSON.stringify(e.args||{},null,2))}</pre><div class="row"><button onclick="perm('${esc(e.request_id)}','deny')">Deny</button><button onclick="perm('${esc(e.request_id)}','allow')">Allow Once</button><button onclick="perm('${esc(e.request_id)}','always')">Always</button></div></div>`}
async function perm(id,d){await api('/api/tools/permission',{method:'POST',body:JSON.stringify({tool:state.permission.tool,request_id:id,decision:d})});state.permission=null;render()}
setInterval(async()=>{try{let a=await api('/api/activity');let e=a.find(x=>x.type==='permission_required'&&!x.resolved);if(e)state.permission=e;state.activity=a;render()}catch{}},1000);load();
